<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ms_customer_model extends CI_Model
{

    public $table = 'ms_customer';
    public $id = 'id_customer';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        // $this->db->order_by($this->id, $this->order);

        // return $this->db->get($this->table)->result();

//         $this->db->select('*');
// $this->db->from('ms_customer');
// $this->db->join('transaksi_h', 'ms_customer.id_customer = transaksi_h.id_customer');
// $query = $this->db->get($this->table)->result();

$this->db->select('ms_customer.*,
transaksi_h.*');
$this->db->from('ms_customer');
$this->db->join('transaksi_h', 'ms_customer.id_customer =transaksi_h.id_customer');
// $this->db->join('produk', 'produk.id_produk = marketing.id_produk');
// $this->db->group_by('nama_customer');
// $this->db->order_by('nama_customer', 'ASC');
// $this->db->order_by('tgl_buat', 'DESC');
$query = $this->db->get();
return $query->result();
    }

    function get_allcust()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {

    $this->db->select('ms_customer.*,
transaksi_h.*');
$this->db->from('ms_customer');
$this->db->join('transaksi_h', 'ms_customer.id_customer =transaksi_h.id_customer');
$this->db->where('ms_customer.id_customer',$id);

$query = $this->db->get();
return $query->row();



        // $this->db->where($this->id, $id);
        // return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_customer', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('phone', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_customer', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('phone', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


    
    public function CreateCode()
    {
        $this->db->select('RIGHT(transaksi_h.nomer_transaksi,5) as nomer_transaksi', FALSE);
        $this->db->order_by('nomer_transaksi', 'DESC');
        $this->db->limit(1);
        $query = $this->db->get('transaksi_h');
        if ($query->num_rows() <> 0) {
            $data = $query->row();
            $kode = intval($data->nomer_transaksi) + 1;
        } else {
            $kode = 1;
        }
        $thn = date('Y');
        $bln = date('m');
        $batas = str_pad($kode, 4, "0", STR_PAD_LEFT);
      

        $kodetampil = "SO" ."/". $thn ."-". $bln."/". $batas;
        return $kodetampil;
    }

    // insert data
    function insert($datacustomer)
    {
        $this->db->insert($this->table, $datacustomer);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ms_customer_model.php */
/* Location: ./application/models/Ms_customer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-08-05 19:04:03 */
/* http://harviacode.com */