<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaksi_h_model extends CI_Model
{

    public $table = 'transaksi_h';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_customer,nomer_transaksi,tanggal_transaksi,total_transaksi');
        $this->datatables->from('transaksi_h');
        //add this line for join
        //$this->datatables->join('table2', 'transaksi_h.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('transaksi_h/read/$1'),'Read')." | ".anchor(site_url('transaksi_h/update/$1'),'Update')." | ".anchor(site_url('transaksi_h/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nomer_transaksi', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('total_transaksi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nomer_transaksi', $q);
	$this->db->or_like('tanggal_transaksi', $q);
	$this->db->or_like('total_transaksi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($datatransaksi)
    {
        $this->db->insert($this->table, $datatransaksi);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaksi_h_model.php */
/* Location: ./application/models/Transaksi_h_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-08-05 16:52:11 */
/* http://harviacode.com */